package net._100steps.labelsys.service.model;
// Generated 2015-2-1 23:54:58 by Hibernate Tools 3.4.0.CR1

/**
 * Entities generated by hbm2java
 */
public class Entity{

	private int id;
	private int systemId;
	private int moduleId;
	private int foreignKey;

	public Entity() {
	}

	public Entity(int systemId, int moduleId, int foreignKey) {
		this.systemId = systemId;
		this.moduleId = moduleId;
		this.foreignKey = foreignKey;
	}
	public Entity(Entity entity) {
		this.id = entity.id;
		this.systemId = entity.systemId;
		this.moduleId = entity.moduleId;
		this.foreignKey = entity.foreignKey;
	}
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getSystemId() {
		return this.systemId;
	}

	public void setSystemId(int systemId) {
		this.systemId = systemId;
	}

	public int getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(int moduleId) {
		this.moduleId = moduleId;
	}

	public int getForeignKey() {
		return this.foreignKey;
	}

	public void setForeignKey(int foreignKey) {
		this.foreignKey = foreignKey;
	}

}
