package net._100steps.labelsys.service.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2015-2-1 23:54:58 by Hibernate Tools 3.4.0.CR1

/**
 * Labels generated by hbm2java
 */
@Entity
@Table(name = "labels")
public class Label implements Serializable
{
	/**
	 * version 1.0
	 */
	private static final long serialVersionUID = 1L;

	private int id;
	private int moduleId;
	private String name;

	public Label()
	{
		
	}

	public Label(int moduleId, String name)
	{
		this.moduleId = moduleId;
		this.name = name;
	}

	public Label(Label label)
	{
		this.id = label.id;
		this.moduleId = label.moduleId;
		this.name = label.name;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(updatable=false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name="module_id")
	public int getModuleId()
	{
		return this.moduleId;
	}

	public void setModuleId(int moduleId)
	{
		this.moduleId = moduleId;
	}

	@Column
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

}
