package net._100steps.labelsys.service.model;
// Generated 2015-2-1 23:54:58 by Hibernate Tools 3.4.0.CR1

/**
 * Modules generated by hbm2java
 */
public class Module{

	private int id;
	private String name;

	public Module() {
	}

	public Module(String name) {
		this.name = name;
	}
	public Module(Module module) {
		this.id = module.id;
		this.name = module.name;
	}
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
